### ISSUE TITLE
Acentos

### ISSUE THREAD

**Issue by nandomaciel** [carvalheirafc/lab6#1]
@carvalheirafc 
Essa função ainda não trata os acentos.

**Comment by carvalheirafc** [comment]
é man tava vendo aqui pra remover os acentos vai ter que trabalhar sobre o encoder do texto. como ISO-Latim-1, UTF-8 , etc. Acho melhor deixar do jeito que tá mesmo, usando a flag ispunct na função remove.
Ta fazendo o trabalho da maneira correta e a comparação tá funcionando mesmo com acento. ehheeh
